# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
      - name: Delete huge unnecessary tools folder
        run: |
          sudo apt-get update
          sudo snap remove lxd
          sudo snap remove core20
          sudo apt autoremove -y --purge apache2 java-common postgresql-14 postgresql-client-14 microsoft-edge-stable gcc gcc-9 gcc-10 gcc-11 gcc-12 gcc-13 heroku
          sudo apt-get remove -y 'php.*'
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo rm -rf /usr/local/lib/node_modules /usr/local/aws-cli /usr/local/aws-sam-cli /usr/local/n /usr/local/julia1.10.0 /usr/local/share/chromium /usr/local/share/powershell /usr/share/swift /usr/share/gradle-8.5 /usr/share/miniconda /usr/share/sbt /usr/share/az_9.3.0 /usr/share/kotlinc /usr/local/bin/aliyun /usr/local/bin/azcopy /usr/local/bin/pulumi* /usr/local/bin/minikube /usr/local/bin/node /usr/local/bin/oc
          sudo rm -rf /opt/hostedtoolcache
          df -h
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest black isort
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install Packages
        uses: ConorMacBride/install-package@v1
        with:
          apt: ffmpeg
      - name: start crawler
        run: |
          scrapy crawl youtuber
      - name: start download
        run: |
          python3 main.py
      - name: package
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: videos/
